# requirement
# brew tap laishulu/macism
# brew install macism

theme = "solarized_light"

[editor]
line-number = "relative"
cursorline = true

[editor.statusline]
left = ["mode", "spinner", "read-only-indicator", "file-modification-indicator"]

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"

[editor.whitespace.render]
space = "all"

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true
wrap-indicator = ""

# macos automatically swith keylayout to en
[keys.normal]
"esc" = [":sh macism com.apple.keylayout.ABC", "normal_mode"]
[keys.insert]
"esc" = [":sh macism com.apple.keylayout.ABC", "normal_mode"]
