[editor]
line-number = "relative"
cursorline = true

[editor.statusline]
left = ["mode", "spinner", "read-only-indicator", "file-modification-indicator"]

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"

[editor.whitespace.render]
space = "all"

[editor.indent-guides]
render = true

