# brew install texlab
# brew install marksman
# brew install --cask oracle-jdk
# brew install ltex-ls or HOMEBREW_BOTTLE_DOMAIN= brew install ltex-ls
# brew install quantonganh/tap/snippets-ls

[language-server.texlab.config.texlab]
build.args = [
    "-pdf",
    "-xelatex",
    "-auxdir=.aux",
    "-interaction=nonstopmode",
    "-synctex=1",
    "%f"
]
build.onSave = true
# build.forwardSearchAfter = true
forwardSearch.executable = "sioyek"
forwardSearch.args = [
    "--reuse-window",
    "--execute-command",
    "toggle_synctex",
    "--inverse-search",
    "hx -r -g \"%%1:%%2\"",
    "--forward-search-file",
    "%f",
    "--forward-search-line",
    "%l",
    "%p",  
]
chktex.onEdit = true

# please enter the absolute address in args.
[language-server.tex-snippets-ls]
command = "snippets-ls"
args = [ "-config", "/Users/wujc/.config/helix/tex-snippets.json" ]

[[language]]
name = "markdown"
language-servers = [ "marksman", "ltex-ls", "tex-snippets-ls" ]
[language.auto-pairs]
'(' = ')'
'$' = '$'
'[' = ']'
'`' = '`'
'{' = '}'
'*' = '*'
'~' = '~'

[[language]]
name = "latex"
language-servers = [ "texlab", "ltex-ls", "tex-snippets-ls" ]
