# brew install texlab
# brew install marksman
# brew install ltex-ls

[language-server.texlab.config.texlab]
build.args = [
    "-pdf",
    "-xelatex",
    "-auxdir=.aux",
    "-interaction=nonstopmode",
    "-synctex=1",
    "%f"
]
build.onSave = true
build.forwardSearchAfter = true
forwardSearch.executable = "sioyek"
forwardSearch.args = [
    "--reuse-window",
    "--execute-command",
    "toggle_synctex",
    "--inverse-search",
    "hx -r -g \"%%1:%%2\"",
    "--forward-search-file",
    "%f",
    "--forward-search-line",
    "%l",
    "%p",  
]
chktex.onEdit = true

[[language]]
name = "markdown"
language-servers = [ "marksman", "ltex-ls" ]
